@E_Commerce.web_HostAddress = http://localhost:5075

GET {{E_Commerce.web_HostAddress}}/weatherforecast/
Accept: application/json

### Get Products
GET {{E_Commerce.web_HostAddress}}/api/Products

### Get Product by Id
@Id = 10
GET {{E_Commerce.web_HostAddress}}/api/Products/{{id}}
